# Copyright (c) 2009-2014 Simon Kennedy <sffjunkie+code@gmail.com>

from mogul.media import localize
_ = localize()

# http://www.fourcc.org/codecs.php
FOUR_CC = {
    '3IV1': _('3ivx'),
    '3IV2': _('3ivx'),
    '8BPS': _('Quicktime RLE codec RGB Planar Format'),
    'AASC': _('Autodesk Animator Studio'),
    'ABYR': _('Kensington?'),
    'ADV1': _('Loronix WaveCodec'),
    'ADVJ': _('Avid M-JPEG'),
    'AEMI': _('Array VideoONE MPEG1-I Capture'),
    'AFLC': _('Autodesk Animator FLC'),
    'AFLI': _('Autodesk Animator FLI'),
    'AJPG': _('22fps JPEG based codec'),
    'AMPG': _('Array VideoONE MPEG'),
    'ANIM': _('Intel?'),
    'AP41': _('AngelPotion Definitive'),
    'ASLC': _('Alparysoft Lossless'),
    'ASV1': _('Asus Video'),
    'ASV2': _('Asus Video 2'),
    'ASVX': _('Asus Video 2.0'),
    'AUR2': _('Aura 2 YUV 422'),
    'AURA': _('Aura 2 YUV 411'),
    'avc1': _('H.264'),
    'AVRn': _('Avid M-JPEG'),
    'BA81': _('Raw 8 bit RGB Bayer'),
    'BINK': _('Bink Video'),
    'BLZ0': _('Blizzard MPEG 4'),
    'BT20': _('Prosumer Video'),
    'BTCV': _('Composite Video Codec'),
    'BW10': _('Broadway MPEG'),
    'BYR1': _('Raw 8 bit RGB Bayer'),
    'BYR2': _('Raw 16 bit RGB Bayer'),
    'CC12': _('YUV12 Codec'),
    'CDVC': _('Canopus DV Codec'),
    'CFCC': _('DPS Perception'),
    'CGDI': _('Camcorder Video'),
    'CHAM': _('Caviara Champagne'),
    'CJPG': _('WebCam JPEG'),
    'CMYK': _('Uncompressed CMYK'),
    'CPLA': _('YUV 4;2:0'),
    'CRAM': _('Microsoft Video 1'),
    'CSCD': _('CamStudio Codec'),
    'CTRX': _('Citrix Scaleable Video Codec'),
    'CVID': _('Cinepak'),
    'CWLT': _('Color WLT DIB'),
    'CXY1': _('Conexant YUV 4:1:1'),
    'CXY2': _('Conexant YUV 4:2:2'),
    'CYUV': _('Creative YUV'),
    'D261': _('H.261'),
    'D263': _('H.263'),
    'davc': _('MPEG-4/H.264'),
    'DCL1': _('Data Connection Conferencing Codec'),
    'DCL2': _('Data Connection Multimedia Conferencing Codec'),
    'DCL3': _('Data Connection Enhanced Conferencing Codec'),
    'DCL4': _('Data Connection Extended Conferencing Codec'),
    'DCL5': _('Data Connection Media Conferencing Codec'),
    'DIV3': _('DivX MPEG-4'),
    'DIV4': _('DivX MPEG-4'),
    'DIV5': _('DivX MPEG-4'),
    'DIVX': _('DivX'),
    'divx': _('DivX'),
    'DM4V': _('MPEG-4'),
    'dmb1': _('Rainbow Runner'),
    'DMB2': _('Paradigm M-JPEG'),
    'DMK2': _('?'),
    'DSVD': _('DV Codec'),
    'DUCK': _('TrueMotion S'),
    'dv25': _('DVCPRO'),
    'dv50': _('DVCPRO50'),
    'DVAN': _('?'),
    'DVCS': _('DV Video'),
    'DVE2': _('DVE-2 Video Conferencing Codec'),
    'dvh1': _('SMPTE 370M'),
    'dvhd': _('50Mbps Consumer DV'),
    'dvsd': _('25Mbps Consumer DV'),
    'DVSD': _('DV Video'),
    'dvsl': _('12.5Mbps Consumer DV'),
    'DVX1': _('DVX1000SP Video Decoder'),
    'DVX2': _('DVX2000SP Video Decoder'),
    'DVX3': _('DVX3000SP Video Decoder'),
    'DX50': _('DivX MPEG-4 version 5'),
    'DXGM': _('?'),
    'DXTC': _('DirectX Texture Compression'),
    'DXTn': _('DirectX Compressed Texture'),
    'EKQ0': _('Elsa Quick Codec'),
    'ELK0': _('?'),
    'EM2V': _('Etymonix MPEG-2 Video'),
    'ES07': _('Eyestream 7 Codec'),
    'ESCP': _('Escape'),
    'ETV1': _('eTreppid Video Codec'),
    'ETV2': _('eTreppid Video Codec'),
    'ETVC': _('eTreppid Video Codec'),
    'FFV1': _('FFMPEG Codec'),
    'FLJP': _('Field Encoded Motion JPEG'),
    'FMP4': _('FFMpeg'),
    'FMVC': _('FM Screen Capture Codec'),
    'FPS1': _('Fraps Codec'),
    'FRWA': _('Forward Motion JPEG with alpha channel'),
    'FRWD': _('Forward Motion JPEG'),
    'FVF1': _('Fractal Video Frame'),
    'GEOX': _('GEOMPEG4'),
    'GJPG': _('GT891x Codec'),
    'GLZW': _('Motion LZW'),
    'GPEG': _('Motion JPEG'),
    'GWLT': _('Greyscale WLT DIB'),
    'H260': _('ITU H.260'),
    'H261': _('ITU H.261'),
    'H262': _('ITU H.262'),
    'H263': _('ITU H.263'),
    'H264': _('ITU H.264'),
    'H265': _('ITU H.265'),
    'H266': _('ITU H.266'),
    'H267': _('ITU H.267'),
    'H268': _('ITU H.268'),
    'H269': _('ITU H.269'),
    'HDYC': _('Raw YUV 4:2:2'),
    'HFYU': _('Huffman Lossless Codec'),
    'HMCR': _('Rendition Motion Compensation Format'),
    'HMRR': _('Rendition Motion Compensation Format'),
    'i263': _('ITU H.263'),
    'IAN ': _('Indeo 4 Codec'),
    'ICLB': _('CellB Video Conferencing Codec'),
    'IGOR': _('PowerDVD'),
    'IJPG': _('Intergraph JPEG'),
    'ILVC': _('Layered Video'),
    'ILVR': _('ITU H.263+ Codec'),
    'IPDV': _('Giga AVI DV Codec'),
    'IR21': _('Indeo 2.1'),
    'IRAW': _('Intel Uncompressed UYUV'),
    'ISME': _('?'),
    'IV30': _('Indeo 3'),
    'IV31': _('Indeo 3'),
    'IV32': _('Indeo 3.2'),
    'IV33': _('Indeo 3'),
    'IV34': _('Indeo 3'),
    'IV35': _('Indeo 3'),
    'IV36': _('Indeo 3'),
    'IV37': _('Indeo 3'),
    'IV38': _('Indeo 3'),
    'IV39': _('Indeo 3'),
    'IV40': _('Indeo Interactive'),
    'IV41': _('Indeo Interactive'),
    'IV42': _('Indeo Interactive'),
    'IV43': _('Indeo Interactive'),
    'IV44': _('Indeo Interactive'),
    'IV45': _('Indeo Interactive'),
    'IV46': _('Indeo Interactive'),
    'IV47': _('Indeo Interactive'),
    'IV48': _('Indeo Interactive'),
    'IV49': _('Indeo Interactive'),
    'IV50': _('Indeo Interactive'),
    'JBYR': _('?'),
    'jpeg': _('JPEG Still Image'),
    'JPEG': _('JPEG Still Image'),
    'JPGL': _('JPEG Light'),
    'KMVC': _('?'),
    'L261': _('LEAD H.261'),
    'L263': _('LEAD H.263'),
    'LBYR': _('?'),
    'LCMW': _('LEAD MCMW Video Codec'),
    'LCW2': _('LEAD MJPEG2000'),
    'LEAD': _('LEAD Video Codec'),
    'LGRY': _('Greyscale Image'),
    'LJ11': _('LEAD JPEG 4:1:1'),
    'LJ22': _('LEAD JPEG 4:2:2'),
    'LJ2K': _('LEAD MJPEG 2000'),
    'LJ44': _('LEAD JPEG 4:4:4'),
    'Ljpg': _('LEAD MJPEG Codec'),
    'LMP2': _('LEAD MPEG-2 Video Codec'),
    'LMP4': _('LEAD MPEG-4 Video Codec'),
    'LSVC': _('Lightning Strike Video Codec'),
    'LSVM': _('Lightning Strike Video Codec'),
    'LSVX': _('Lightning Strike Video Codec'),
    'LZO1': _('Lempel-Ziv-Oberhumer Codec'),
    'M261': _('H.261'),
    'M263': _('H.263'),
    'M4CC': _('MPEG-4'),
    'm4cc': _('MPEG-4'),
    'M4S2': _('MPEG-4 (Automatic WMP download)'),
    'MC12': _('Motion Compensation Format'),
    'MCAM': _('Motion Compensation Format'),
    'MJ2C': _('Motion JPEG 2000'),
    'mJPG': _('Motion JPEG Including Huffman Tables'),
    'MJPG': _('Motion JPEG'),
    'MMES': _('MPEG-2 ES'),
    'MP2A': _('MPEG-2 Audio'),
    'MP2T': _('MPEG-2 Transport Stream'),
    'MP2V': _('MPEG-2 Video'),
    'MP42': _('MPEG-4'),
    'MP43': _('MPEG-4'),
    'MP4A': _('MPEG-4 Audio'),
    'MP4S': _('MPEG-4 (Sharp Digital Camera)'),
    'MP4T': _('MPEG-4 Transport Stream'),
    'mp4v': _('MPEG-4'),
    'MP4V': _('MPEG-4'),
    'MPEG': _('MPEG?'),
    'MPG4': _('MPEG-4'),
    'MPGI': _('MPEG'),
    'MR16': _('?'),
    'MRCA': _('Mrcodec'),
    'MRLE': _('microsoft RLE'),
    'MSVC': _('Microsoft Video 1'),
    'MSZH': _('AVImszh'),
    'MTX1': _('Matrox?'),
    'MTX2': _('Matrox?'),
    'MTX3': _('Matrox?'),
    'MTX4': _('Matrox?'),
    'MTX5': _('Matrox?'),
    'MTX6': _('Matrox?'),
    'MTX7': _('Matrox?'),
    'MTX8': _('Matrox?'),
    'MTX9': _('Matrox?'),
    'MVI1': _('Motion Pixels MVI1 Codec'),
    'MVI2': _('Motion Pixels MVI2 Codec'),
}
