# Copyright (c) 2009-2014 Simon Kennedy <sffjunkie+code@gmail.com>

from mogul.media import localize
_ = localize()

ID3_GENRE = {
    0: _('Blues'),
    1: _('Classic Rock'),
    2: _('Country'),
    3: _('Dance'),
    4: _('Disco'),
    5: _('Funk'),
    6: _('Grunge'), 
    7: _('Hip-Hop'),
    8: _('Jazz'),
    9: _('Metal'), 
    10: _('New Age'),  
    11: _('Oldies'),
    12: _('Other'),
    13: _('Pop'),
    14: _('R&B'),
    15: _('Rap'),
    16: _('Reggae'),
    17: _('Rock'),
    18: _('Techno'),
    19: _('Industrial'),
    20: _('Alternative'),
    21: _('Ska'),
    22: _('Death Metal'),
    23: _('Pranks'),
    24: _('Soundtrack'),
    25: _('Euro-Techno'),
    26: _('Ambient'),
    27: _('Trip-Hop'),
    28: _('Vocal'),
    29: _('Jazz+Funk'),
    30: _('Fusion'),
    31: _('Trance'),
    32: _('Classical'),
    33: _('Instrumental'),
    34: _('Acid'),
    35: _('House'),
    36: _('Game'),
    37: _('Sound Clip'),
    38: _('Gospel'),
    39: _('Noise'),
    40: _('Alternative Rock'),
    41: _('Bass'),
    42: _('Soul'),
    43: _('Punk'),
    44: _('Space'),
    45: _('Meditative'),
    46: _('Instrumental Pop'),
    47: _('Instrumental Rock'),  
    48: _('Ethnic'),
    49: _('Gothic'),
    50: _('Darkwave'),
    51: _('Techno-Industrial'),
    52: _('Electronic'),
    53: _('Pop-Folk'),
    54: _('Eurodance'),
    55: _('Dream'),
    56: _('Southern Rock'),
    57: _('Comedy'),
    58: _('Cult'),
    59: _('Gangsta'),
    60: _('Top 40'),
    61: _('Christian Rap'),
    62: _('Pop/Funk'),
    63: _('Jungle'),
    64: _('Native US'),
    65: _('Cabaret'),
    66: _('New Wave'),
    67: _('Psychadelic'),
    68: _('Rave'),
    69: _('Showtunes'),
    70: _('Trailer'),
    71: _('Lo-Fi'),
    72: _('Tribal'),
    73: _('Acid Punk'),
    74: _('Acid Jazz'),
    75: _('Polka'),
    76: _('Retro'),
    77: _('Musical'),
    78: _('Rock & Roll'),
    79: _('Hard Rock'),
    80: _('Folk'),
    81: _('Folk-Rock'),
    82: _('National Folk'),
    83: _('Swing'),
    84: _('Fast Fusion'),
    85: _('Bebob'),
    86: _('Latin'),
    87: _('Revival'),
    88: _('Celtic'),
    89: _('Bluegrass'),
    90: _('Avantgarde'),
    91: _('Gothic Rock'),
    92: _('Progressive Rock'),
    93: _('Psychedelic Rock'),
    94: _('Symphonic Rock'),
    95: _('Slow Rock'),
    96: _('Big Band'),
    97: _('Chorus'),
    98: _('Easy Listening'),
    99: _('Acoustic'),
    100: _('Humour'),
    101: _('Speech'),
    102: _('Chanson'),
    103: _('Opera'),
    104: _('Chamber Music'),
    105: _('Sonata'),
    106: _('Symphony'),
    107: _('Booty Bass'),
    108: _('Primus'),
    109: _('Porn Groove'),
    110: _('Satire'),
    111: _('Slow Jam'),
    112: _('Club'),
    113: _('Tango'),
    114: _('Samba'),
    115: _('Folklore'),
    116: _('Ballad'),
    117: _('Power Ballad'),
    118: _('Rhythmic Soul'),
    119: _('Freestyle'),
    120: _('Duet'),
    121: _('Punk Rock'),
    122: _('Drum Solo'),
    123: _('Acapella'),
    124: _('Euro-House'),
    125: _('Dance Hall'),
    126: _('Goa'),
    127: _('Drum & Bass'),
    128: _('Club: \'House'),
    129: _('Hardcore'),
    130: _('Terror'),
    131: _('Indie'),
    132: _('BritPop'),
    133: _('Negerpunk'),
    134: _('Polsk Punk'),
    135: _('Beat'),
    136: _('Christian Gangsta Rap'),
    137: _('Heavy Metal'),
    138: _('Black Metal'),
    139: _('Crossover'),
    140: _('Contemporary Christian'),
    141: _('Christian Rock'),
    142: _('Merengue'),
    143: _('Salsa'),
    144: _('Thrash Metal'),
    145: _('Anime'),
    146: _('JPop'),
    147: _('Synthpop'),
}

ID3_IMAGE_TYPE = {
    0x00: _('Other'),
    0x01: _('32x32 pixels file icon (PNG only)'),
    0x02: _('Other file icon'),
    0x03: _('Cover (front)'),
    0x04: _('Cover (back)'),
    0x05: _('Leaflet page'),
    0x06: _('Media (e.g. label side of CD)'),
    0x07: _('Lead artist/lead performer/soloist'),
    0x08: _('Artist/performer'),
    0x09: _('Conductor'),
    0x0A: _('Band/Orchestra'),
    0x0B: _('Composer'),
    0x0C: _('Lyricist/text writer'),
    0x0D: _('Recording Location'),
    0x0E: _('During recording'),
    0x0F: _('During performance'),
    0x10: _('Movie/video screen capture'),
    0x11: _('A bright coloured fish'),
    0x12: _('Illustration'),
    0x13: _('Band/artist logotype'),
    0x14: _('Publisher/Studio logotype'),
}
